### PR TITLE
Upgrade to libsignal-protocol 0.32

### PR DESCRIPTION
**Pull request by boxdot**

### CODE REVIEW

**Comment by boxdot** [comment]
Based on https://github.com/whisperfish/libsignal-service-rs/pull/245. Can be merged when this PR lands.

**Comment by Schmiddiii** [comment]
Am I missing something or does this not update the libsignal-commit to the `update-libsignal-0.32`-branch?

**Comment by Schmiddiii** [comment]
I added that patch but it changed nothing.

**Comment by gferon** [comment]
Thanks for the patches @boxdot, let's 🚀 it and squash bugs at they arise.

**Pull request merged**
