### PR TITLE
Add support for stickers

### PR DESCRIPTION
**Pull request by R-D-C-N**
Using the recent additions to libsignal-service-rs, I've added several functions to the Manager and Store (and by extension the sled-store).

In `Manager::receive_messages` I also handle the `StickerPackOperation`s in sync messages so that sticker packs sync across clients, however, because the stream state doesn't have access to a push service (as far as I know) the sticker packs can't get their manifests. So I've decided to put them in a queue which can be processed by manager with `process_sticker_pack_queue` I'm open to suggestions, if you think there is a better way to handle this.

Things that have been tested/need to be tested:
- [x] Sticker Decryption/Retrieval
- [x] Manifest Decryption/Retrieval
- [x] Sticker Pack Storage and Iteration
- [x] Sticker Syncing (Receiving)
- [x] Sticker Syncing (Sending)

I will continue to update this as I start testing more features.
<sub>If you have any ideas for anything that would fit with this pr I could try implementing them and including them in the pr</sub>

### CODE REVIEW

**Comment by gferon** [comment]
Really nice addition, thanks for working on it!

**Comment by R-D-C-N** [comment]
Thank you,
You can wait until I'm done. If you want, you can also check any of the tested/untested changes function as intended and give feedback

**Comment by R-D-C-N** [comment]
Sorry for the inactivity; I got busy. I think this PR is ready

**Comment by gferon** [comment]
@R-D-C-N I must apologize for the long delay. Thanks a lot for adding support for stickers! I took over your PR, reworked a few things, and just finished re-testing. I'll add some finishing touches and merge it ASAP!

**Pull request merged**
